name: CI - Build MongoDB Console Apps

on:
  workflow_dispatch:    # Allows manual trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup MSBuild for .NET Framework project
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        
      # Restore & Build .NET Framework project
      - name: Restore NuGet Packages (.NET Framework)
        run: nuget restore MongoDBConsoleApp/MongoDBConsoleApp/MongoDBConsoleApp.csproj

      - name: Build .NET Framework Project
        run: msbuild MongoDBConsoleApp/MongoDBConsoleApp/MongoDBConsoleApp.csproj

       # Setup .NET SDK for .NET Core project
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.0

      # Restore & Build .NET Core project
      - name: Restore & Build .NET Core Project
        run: |
          dotnet restore MongoDBConsoleApp/MongoEFCoreConsoleApp/MongoEFCoreConsoleApp.csproj
          dotnet build MongoDBConsoleApp/MongoEFCoreConsoleApp/MongoEFCoreConsoleApp.csproj --configuration Release
     
